/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.JScrollPane;
import javax.swing.JTextField;

/**
 *
 * @author JoãoVitor
 */
public class ViewCriarAtributo extends javax.swing.JFrame {

    /**
     * Creates new form ViewCriarAtributo
     */
    public ViewCriarAtributo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelNomeAtributo = new javax.swing.JLabel();
        textNomeAtributo = new javax.swing.JTextField();
        labelChavePrimaria = new javax.swing.JLabel();
        ComboBoxChavePrimaria = new javax.swing.JComboBox();
        labelTipoAtributo = new javax.swing.JLabel();
        ComboBoxTipoAtributo = new javax.swing.JComboBox();
        labelNotNULL = new javax.swing.JLabel();
        ComboBoxNotNull = new javax.swing.JComboBox();
        btnCriarAtributo = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        textM = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListentidades = new javax.swing.JList();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        comboboxChaveEstrangeira = new javax.swing.JComboBox();
        btncancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        labelNomeAtributo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        labelNomeAtributo.setText("Nome do Atributo:");

        textNomeAtributo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textNomeAtributoActionPerformed(evt);
            }
        });

        labelChavePrimaria.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        labelChavePrimaria.setForeground(new java.awt.Color(255, 0, 0));
        labelChavePrimaria.setText("Chave Primaria:");

        ComboBoxChavePrimaria.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        ComboBoxChavePrimaria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBoxChavePrimariaActionPerformed(evt);
            }
        });

        labelTipoAtributo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        labelTipoAtributo.setText("Tipo do Atributo:");

        ComboBoxTipoAtributo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        labelNotNULL.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        labelNotNULL.setText("Não Nulo:");

        ComboBoxNotNull.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnCriarAtributo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icone/Salvar.png"))); // NOI18N
        btnCriarAtributo.setText("Salvar");

        jLabel1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel1.setText("Tamanho:");

        jListentidades.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jListentidades);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Selecione uma Entidade Cadastrada:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Chave Estrangeira");

        comboboxChaveEstrangeira.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btncancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icone/Cancelar.gif"))); // NOI18N
        btncancelar.setText("Cancelar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelNomeAtributo)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(textNomeAtributo, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(ComboBoxTipoAtributo, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(textM, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(labelTipoAtributo))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelNotNULL)
                            .addComponent(ComboBoxNotNull, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 13, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(labelChavePrimaria, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ComboBoxChavePrimaria, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addComponent(btnCriarAtributo)))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btncancelar)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(comboboxChaveEstrangeira, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelNomeAtributo, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelTipoAtributo)
                            .addComponent(labelNotNULL))
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ComboBoxTipoAtributo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)
                            .addComponent(textM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ComboBoxNotNull, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(textNomeAtributo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelChavePrimaria)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ComboBoxChavePrimaria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboboxChaveEstrangeira, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btncancelar)
                    .addComponent(btnCriarAtributo))
                .addGap(37, 37, 37))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textNomeAtributoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textNomeAtributoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textNomeAtributoActionPerformed

    private void ComboBoxChavePrimariaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBoxChavePrimariaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboBoxChavePrimariaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewCriarAtributo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewCriarAtributo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewCriarAtributo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewCriarAtributo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewCriarAtributo().setVisible(true);
            }
        });
    }

    public JComboBox getComboBoxChavePrimaria() {
        return ComboBoxChavePrimaria;
    }

    public void setComboBoxChavePrimaria(JComboBox ComboBoxChavePrimaria) {
        this.ComboBoxChavePrimaria = ComboBoxChavePrimaria;
    }

    public JComboBox getComboBoxNotNull() {
        return ComboBoxNotNull;
    }

    public void setComboBoxNotNull(JComboBox ComboBoxNotNull) {
        this.ComboBoxNotNull = ComboBoxNotNull;
    }

    public JComboBox getComboBoxTipoAtributo() {
        return ComboBoxTipoAtributo;
    }

    public void setComboBoxTipoAtributo(JComboBox ComboBoxTipoAtributo) {
        this.ComboBoxTipoAtributo = ComboBoxTipoAtributo;
    }

    public JButton getBtnCriarAtributo() {
        return btnCriarAtributo;
    }

    public void setBtnCriarAtributo(JButton btnCriarAtributo) {
        this.btnCriarAtributo = btnCriarAtributo;
    }

    public JLabel getLabelChavePrimaria() {
        return labelChavePrimaria;
    }

    public void setLabelChavePrimaria(JLabel labelChavePrimaria) {
        this.labelChavePrimaria = labelChavePrimaria;
    }

    public JLabel getLabelNomeAtributo() {
        return labelNomeAtributo;
    }

    public void setLabelNomeAtributo(JLabel labelNomeAtributo) {
        this.labelNomeAtributo = labelNomeAtributo;
    }

    public JLabel getLabelNotNULL() {
        return labelNotNULL;
    }

    public void setLabelNotNULL(JLabel labelNotNULL) {
        this.labelNotNULL = labelNotNULL;
    }

    public JLabel getLabelTipoAtributo() {
        return labelTipoAtributo;
    }

    public void setLabelTipoAtributo(JLabel labelTipoAtributo) {
        this.labelTipoAtributo = labelTipoAtributo;
    }

    public JTextField getTextNomeAtributo() {
        return textNomeAtributo;
    }

    public void setTextNomeAtributo(JTextField textNomeAtributo) {
        this.textNomeAtributo = textNomeAtributo;
    }
    
    public JLabel getjLabel1() {
        return jLabel1;
    }

    public void setjLabel1(JLabel jLabel1) {
        this.jLabel1 = jLabel1;
    }

    public JTextField getTextM() {
        return textM;
    }

    public void setTextM(JTextField textM) {
        this.textM = textM;
    }
    
    
    public JScrollPane getjScrollPane1() {
        return jScrollPane1;
    }

    public void setjScrollPane1(JScrollPane jScrollPane1) {
        this.jScrollPane1 = jScrollPane1;
    }

    public JLabel getjLabel2() {
        return jLabel2;
    }

    public void setjLabel2(JLabel jLabel2) {
        this.jLabel2 = jLabel2;
    }

    public JButton getBtncancelar() {
        return btncancelar;
    }

    public void setBtncancelar(JButton btncancelar) {
        this.btncancelar = btncancelar;
    }

    public JComboBox getComboboxChaveEstrangeira() {
        return comboboxChaveEstrangeira;
    }

    public void setComboboxChaveEstrangeira(JComboBox comboboxChaveEstrangeira) {
        this.comboboxChaveEstrangeira = comboboxChaveEstrangeira;
    }

    public JLabel getjLabel3() {
        return jLabel3;
    }

    public void setjLabel3(JLabel jLabel3) {
        this.jLabel3 = jLabel3;
    }

    public JList getjListentidades() {
        return jListentidades;
    }

    public void setjListentidades(JList jListentidades) {
        this.jListentidades = jListentidades;
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox ComboBoxChavePrimaria;
    private javax.swing.JComboBox ComboBoxNotNull;
    private javax.swing.JComboBox ComboBoxTipoAtributo;
    private javax.swing.JButton btnCriarAtributo;
    private javax.swing.JButton btncancelar;
    private javax.swing.JComboBox comboboxChaveEstrangeira;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JList jListentidades;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelChavePrimaria;
    private javax.swing.JLabel labelNomeAtributo;
    private javax.swing.JLabel labelNotNULL;
    private javax.swing.JLabel labelTipoAtributo;
    private javax.swing.JTextField textM;
    private javax.swing.JTextField textNomeAtributo;
    // End of variables declaration//GEN-END:variables
}
