/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.JScrollPane;

/**
 *
 * @author JoãoVitor
 */
public class ViewEditarEntidade extends javax.swing.JFrame {

    /**
     * Creates new form ViewEditarEntidade
     */
    public ViewEditarEntidade() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelentidades = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListentidades = new javax.swing.JList();
        btnalterarnomeentidade = new javax.swing.JButton();
        btnexcluirentidade = new javax.swing.JButton();
        btneditaratributos = new javax.swing.JButton();
        btncancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        labelentidades.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        labelentidades.setText("Selecione uma Entidade cadastrada:");
        labelentidades.setToolTipText("");

        jListentidades.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jListentidades);

        btnalterarnomeentidade.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icone/alterar nome.png"))); // NOI18N
        btnalterarnomeentidade.setText("Alterar Nome ");

        btnexcluirentidade.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icone/excluir.png"))); // NOI18N
        btnexcluirentidade.setText("Excluir");
        btnexcluirentidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnexcluirentidadeActionPerformed(evt);
            }
        });

        btneditaratributos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icone/editar.png"))); // NOI18N
        btneditaratributos.setText("Editar Atributo");

        btncancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icone/Cancelar.gif"))); // NOI18N
        btncancelar.setText("Cancelar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelentidades)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 444, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(btnalterarnomeentidade, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btncancelar)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnexcluirentidade, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btneditaratributos)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelentidades)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnalterarnomeentidade)
                    .addComponent(btnexcluirentidade, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btneditaratributos))
                .addGap(29, 29, 29)
                .addComponent(btncancelar)
                .addGap(32, 32, 32))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnexcluirentidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnexcluirentidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnexcluirentidadeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewEditarEntidade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewEditarEntidade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewEditarEntidade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewEditarEntidade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewEditarEntidade().setVisible(true);
            }
        });
    }


    public JButton getBtnalterarnomeentidade() {
        return btnalterarnomeentidade;
    }

    public void setBtnalterarnomeentidade(JButton btnalterarnomeentidade) {
        this.btnalterarnomeentidade = btnalterarnomeentidade;
    }

    public JButton getBtneditaratributos() {
        return btneditaratributos;
    }

    public void setBtneditaratributos(JButton btneditaratributos) {
        this.btneditaratributos = btneditaratributos;
    }

    public JButton getBtnexcluirentidade() {
        return btnexcluirentidade;
    }

    public void setBtnexcluirentidade(JButton btnexcluirentidade) {
        this.btnexcluirentidade = btnexcluirentidade;
    }

    public JList getjListentidades() {
        return jListentidades;
    }

    public void setjListentidades(JList jListentidades) {
        this.jListentidades = jListentidades;
    }

    public JScrollPane getjScrollPane1() {
        return jScrollPane1;
    }

    public void setjScrollPane1(JScrollPane jScrollPane1) {
        this.jScrollPane1 = jScrollPane1;
    }

    public JLabel getLabelentidades() {
        return labelentidades;
    }

    public void setLabelentidades(JLabel labelentidades) {
        this.labelentidades = labelentidades;
    }

    public JButton getBtncancelar() {
        return btncancelar;
    }

    public void setBtncancelar(JButton btncancelar) {
        this.btncancelar = btncancelar;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnalterarnomeentidade;
    private javax.swing.JButton btncancelar;
    private javax.swing.JButton btneditaratributos;
    private javax.swing.JButton btnexcluirentidade;
    private javax.swing.JList jListentidades;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelentidades;
    // End of variables declaration//GEN-END:variables
}
