/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.JScrollPane;

/**
 *
 * @author JoãoVitor
 */
public class ViewEditarDataBase extends javax.swing.JFrame {

    /**
     * Creates new form ViewEditarDataBase
     */
    public ViewEditarDataBase() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labeldatabase = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListdatabases = new javax.swing.JList();
        btnalterarnomedatabase = new javax.swing.JButton();
        btneditarentidade = new javax.swing.JButton();
        btnexcluir = new javax.swing.JButton();
        btncancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        labeldatabase.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        labeldatabase.setText("Selecione um Database cadastrado:");

        jListdatabases.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jListdatabases);

        btnalterarnomedatabase.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icone/alterar nome.png"))); // NOI18N
        btnalterarnomedatabase.setText("Alterar Nome ");

        btneditarentidade.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icone/editar.png"))); // NOI18N
        btneditarentidade.setText("Editar Entidade");

        btnexcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icone/excluir.png"))); // NOI18N
        btnexcluir.setText("Excluir");

        btncancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icone/Cancelar.gif"))); // NOI18N
        btncancelar.setText("Cancelar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 456, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(btnalterarnomedatabase)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btncancelar)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnexcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(27, 27, 27)
                                        .addComponent(btneditarentidade)))))
                        .addGap(0, 8, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labeldatabase)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(labeldatabase)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnalterarnomedatabase)
                    .addComponent(btnexcluir)
                    .addComponent(btneditarentidade))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(btncancelar)
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewEditarDataBase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewEditarDataBase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewEditarDataBase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewEditarDataBase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewEditarDataBase().setVisible(true);
            }
        });
    }

    public JButton getBtnalterarnomedatabase() {
        return btnalterarnomedatabase;
    }

    public void setBtnalterarnomedatabase(JButton btnalterarnomedatabase) {
        this.btnalterarnomedatabase = btnalterarnomedatabase;
    }

    public JButton getBtneditarentidade() {
        return btneditarentidade;
    }

    public void setBtneditarentidade(JButton btneditarentidade) {
        this.btneditarentidade = btneditarentidade;
    }

    public JButton getBtnexcluir() {
        return btnexcluir;
    }

    public void setBtnexcluir(JButton btnexcluir) {
        this.btnexcluir = btnexcluir;
    }

    public JList getjListdatabases() {
        return jListdatabases;
    }

    public void setjListdatabases(JList jListdatabases) {
        this.jListdatabases = jListdatabases;
    }

    public JScrollPane getjScrollPane1() {
        return jScrollPane1;
    }

    public void setjScrollPane1(JScrollPane jScrollPane1) {
        this.jScrollPane1 = jScrollPane1;
    }

    public JLabel getLabeldatabase() {
        return labeldatabase;
    }

    public void setLabeldatabase(JLabel labeldatabase) {
        this.labeldatabase = labeldatabase;
    }

    public JButton getBtncancelar() {
        return btncancelar;
    }

    public void setBtncancelar(JButton btncancelar) {
        this.btncancelar = btncancelar;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnalterarnomedatabase;
    private javax.swing.JButton btncancelar;
    private javax.swing.JButton btneditarentidade;
    private javax.swing.JButton btnexcluir;
    private javax.swing.JList jListdatabases;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labeldatabase;
    // End of variables declaration//GEN-END:variables
}
